### ISSUE TITLE
csprng(x,36) with small values of x returns 'undefined' some of the time

### ISSUE THREAD

**Issue by elisee** [jcoglan/node-csprng#1]
Calling `require('csprng')(x,36)` (with x = 1-3 bits) returns the string `'undefined'` some of the time. 

To reproduce, run:

```
while( csprng(1,36) != 'undefined');
```

This will return almost immediately. Same for 2. 3 takes a while but gets there. I suspect the bug might be present with higher values too but it becomes so rare that it's hard to hit it.

**Comment by jcoglan** [comment]
How does this manifest in Faye?

**Comment by elisee** [comment]
What's Faye?

The `'undefined'` string is returned by `csprng` when `sequin.generate` returns `null` (which shouldn't happen I suppose but it does happen for some values generated with randomBytes).

**Comment by jcoglan** [comment]
Faye is the npm module that `csprng` was written to support, and is the only module depending on it. It was designed to handle large values of `x`, i.e. numbers higher than can be represented using JavaScript numbers. If you only want a small number of bits (< 32) then this module is redundant; you can do this trivially using basic number data.

I wouldn't expect that trying to generate a base-36 digit using only a few bits of data (base-36 digits are 5.17 bits each) would work.
